version: '2.1'
services:
  ogn:
    build: ./ogn
    image: ogn
    restart: always
    environment:
      - LAT=
      - LON=
      - ALT=
      - OGN_DEVICE=
      - OGN_CALLSIGN=

    devices:
      - "/dev/bus/usb"
    expose:
      - "8080"
      - "8082"
      - "8083"
      - "50000"
      - "50001"
    ports:
      - "8082:8082"
      - "8083:8083"
      - "50000:50000"
      - "50001:50001"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS="unix:path=/host/run/dbus/system_bus_socket"
      - PORTAL_LISTENING_PORT=8181
      - PORTAL_SSID=balenaWiFi
      - PORTAL_PASSPHRASE=balenaWiFi
      - ACTIVITY_TIMEOUT=120
    ports:
      - "8181:8181"
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: '1'
